name: Release
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: |
              args: [--frozen-lockfile, --strict-peer-dependencies]
        # for now, skipping eslint
      - run: pnpx -y tsm test.ts
